apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-fullstack-app
  labels:
    app: devops-fullstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-fullstack
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-fullstack
    spec:
      containers:
      - name: app
        image: dheeraj202/devops-fullstack-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "v2.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5